# -*- coding: utf-8 -*-
"""4110E105_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EPL7tlbkGjQGuzy8xVpUWNXUj80FiUcz
"""

a = input('Enter your name:')
print('HEllo ,'+ a)

x = int(input("請輸入："))
x

b = x+30
b

print("this is 4110E105 speaking")
a = input("請收入:")
print(a)

type(a)